[project]
name = "typst-wordometer"
version = "0.1.0"
description = "Add a short description here"
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
test = "typst-test run"

[dependencies]
typst-test = ">=0.0.0.post106+2b4e689,<0.0.1+2b4e689"
